### ISSUE TITLE
A k čemu to jako je?

### ISSUE THREAD

**Issue by karelbilek** [pirati-cz/gapi-sparql#21]

**Comment by lnovy** [comment]
Storage vrstva grafpve databaze. Verze 1.0 je na http://graph.pirati.cz, tohle je verze 3.0 (verzi 2.0 sem nikdy nezacal implementovat, jenom dlouze mluvil o konceptech a mezitim se me myslenky ujali mladsi). Verze 4.0 bude pravdepodobne postavena nad tauchain:
- http://tauchain.org/tauchain.pdf
- https://github.com/naturalog/tauchain

**Comment by jmichalek** [comment]
To vypadá zajímavě. Ty se tím zabýváš? Mohli bychom si na tohle téma někdy
sednout a pokecat. Já bych rád napsal dizertaci o automatizaci práva... :D

**Comment by lnovy** [comment]
Tedka sem si od toho dal chvili pauzu, ale vicemene se to vyvinulo ze zennetu, kterej sem delal.
- http://zennet.sc/

**Comment by karelbilek** [comment]
Pořád nevím, co to znamená :)

Co mám použít za jméno a heslo?

**Comment by scippio** [comment]
Tohle už je docela starý kód... už mám mnohem vymakanější... ale delší dobu jsem teď na tomhle nedělal. Budu pokračovat brzy (týdny... měsíce...) tady: https://github.com/scippio/gapi-sparql

Bude i lepší dokumentace a pořád je to spíš experiment ...
